<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>pdfgear_classic_helper</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AssemblyName>PDFgearClassic</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
